language: node_js
node_js:
  12
cache:
  directories:
    node_modules
before_script:
  - curl --create-dirs -o dist/backend.wasm -GL https://github.com/Symatem/SymatemRust/releases/latest/download/symatem.wasm
script:
  npm test
