language: node_js
node_js:
  - 8.9.3
  - 9
sudo: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
script:
  - npm test
after_success:
  - npm run semantic-release
